import { createStyles, makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(() => createStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    width: 250,
    padding: 20,
    margin: "0 30px 10px 0",
    backgroundColor: "#fff",
    '& > img': {
      alignSelf: 'center',
    },
  },
  salesCircle: {
    borderRadius: "50%",
    position: 'absolute',
    color: "#02c3d9",
    textAlign: 'center',
    width: 32,
    marginTop: "-10px",
    marginLeft: "-10px",
    boxShadow: "0px 0px 30px #ccc",
    left: 0,
    top: 0,
  },
  separator: {
    width: "80%",
    margin: "20px 0 10px 0",
    borderBottom: "1px solid #ccc",
    alignSelf: 'center',
  },
  buyButton: {
    backgroundColor: "#02c3d9",
    borderRadius: "25px",
    border: "none",
    boxSizing: "border-box",
    cursor: "pointer",
    fontWeight: 400,
    color: "#fff",
    fontSize: 12,
    boxShadow: "0px 0px 13px #AFAFAF",
    display: "inline-block",
    height: "40px",
    width: 100,
    margin: "0",
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    padding: "0 10px",
    position: "relative",
    textAlign: "center",
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
    '&:hover': {
      backgroundColor: '#02aabd',
    },
  },
  priceContainer: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  booksWrapper: {
    display: "flex",
    flexWrap: "wrap",
  },
  row: {
    display: 'flex',
  },
  createBookButton: {
    backgroundColor: "#02c3d9",
    borderRadius: "25px",
    border: "none",
    color: "#fff",
    boxSizing: "border-box",
    cursor: "pointer",
    fontWeight: 600,
    display: "inline-block",
    height: 40,
    width: 180,
    margin: 20,
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    position: "relative",
    textAlign: "center",
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
    "&:hover": {
      backgroundColor: "#02aabd",
    },
  },
}));
