import { createStyles, makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(() => createStyles({
  orangeBox: {
    height: 500,
    // backgroundColor: "#ff692e",
    position: "absolute",
    top: 0,
    width: "100%",
  },
  main: {
    position: 'relative',
    height: 500,
    width: "100%",
    paddingTop: 45,
  },
  clock: {
    clipPath: "polygon(0 0, 100% 0%, 100% 49%, 0 49%)",
    // paddingTop: 142,
    marginBottom: "-153px",
    height: 300,
    position: 'relative',
  },
  text: {
    color: '#fff',
    fontSize: 40,
  },
  button: {
    backgroundColor: "#ffd52e",
    borderRadius: "25px",
    border: "none",
    boxSizing: "border-box",
    cursor: "pointer",
    // fontFamily: 'inherit',
    fontWeight: 600,
    boxShadow: "0px 0px 13px #AFAFAF",
    display: "inline-block",
    height: "50px",
    lineHeight: "50px",
    width: 200,
    margin: "0",
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    padding: "0 32px",
    position: "relative",
    textAlign: "center",
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
    '&:hover': {
      backgroundColor: '#e6c029',
    },
  },
  container: {
    position: "relative",
    display: "flex",
    justifyContent: "space-between",
    height: "100%",
    alignItems: "center",
    flexDirection: 'column',
  },
  input: {
    fontWeight: 300,
    fontSize: 32,
    borderRadius: "25px",
    outline: "none",
    border: "none",
    height: 50,
    width: "55%",
    lineHeight: "70px",
    padding: "0 50px 0 18px",
    '&::placeholder': {
      textAlign: 'center',
      // fontFamily: 'IRANSans',
      fontSize: "60%",
    },
  },
}));
