import { createStyles, makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(() => createStyles({
  navbar: {
    display: "flex",
    justifyContent: "space-between",
    position: 'relative',
    alignItems: "center",
    height: 60,
    backgroundColor: "#fff",
    borderBottom: '1px solid #000',
    width: "100%",
    "& a": {
      float: "left",
      fontSize: "16px",
      textAlign: "center",
      padding: "14px 16px",
      margin: "0 25px",
      textDecoration: "none",
    },
  },
  headerList: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 25,
  },
  dropdown: {
    float: "left",
    position: 'relative',
    zIndex: 200,
    "&:hover $dropbtn": {
      backgroundColor: 'orange',
    },
    "&:hover $dropdownContent": {
      display: "block",
    },
  },
  loginbtn: {
    fontSize: "16px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    outline: "none",
    borderRadius: 40,
    width: 130,
    border: '1px solid orange',
    padding: "8px 0",
    backgroundColor: "white",
    margin: "0",
    marginLeft: 25,
    cursor: 'pointer',
  },
  dropbtn: {
    fontSize: "16px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    outline: "none",
    borderRadius: 40,
    width: 130,
    border: '1px solid orange',
    padding: "8px 0",
    backgroundColor: "white",
    margin: "0",
    marginLeft: 25,
  },
  dropdownContent: {
    display: "none",
    position: "absolute",
    backgroundColor: "#eee",
    marginTop: "-7px",
    // @ts-ignore
    zIndex: '-1',
    width: 130,
    marginLeft: 25,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    boxShadow: "0px 8px 16px 0px rgba(0,0,0,0.2)",
    // zIndex: "-1",
    "& a": {
      float: "none",
      color: "black",
      padding: "12px 0",
      margin: 0,
      width: "100%",
      textDecoration: "none",
      display: "block",
      textAlign: "center",
      "&:hover": {
        backgroundColor: "#ddd",
      },
    },
    "& div": {
      float: "none",
      color: "black",
      padding: "12px 0",
      cursor: 'pointer',
      margin: 0,
      width: "100%",
      // fontWeight: 'bold',
      fontSize: "115%",
      textDecoration: "none",
      display: "block",
      textAlign: "center",
      "&:hover": {
        backgroundColor: "#ddd",
      },
    },
  },
}));
