import { createStyles, makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(() => createStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: 250,
    padding: 20,
    margin: "0 10px 10px 0",
    backgroundColor: "#fff",
    '& > img': {
      alignSelf: 'center',
    },
  },
  separator: {
    width: "80%",
    margin: "20px 0 10px 0",
    borderBottom: "1px solid #ccc",
    alignSelf: 'center',
  },
  buyButton: {
    alignSelf: 'center',
    backgroundColor: "#02c3d9",
    color: "#000",
    border: "none",
    boxSizing: "border-box",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    display: "inline-block",
    height: "40px",
    width: "100%",
    margin: "0",
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    padding: "0 10px",
    position: "relative",
    textAlign: "center",
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
    '&:hover': {
      backgroundColor: '#02aabd',
    },
  },
  resultPagination: {
    width: "100%",
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    padding: "20px 10px",
    "& > button": {
      borderRadius: 5,
      padding: 10,
      margin: "0 5px",
      opacity: 1,
      border: "1px solid #000",
    },
    "& p": {
      color: "#000",
    },
  },
  paginationNumbers: {
    display: 'flex',
  },
  paginationButton: {
    borderRadius: "25px",
    boxSizing: "border-box",
    boxShadow: "none",
    cursor: "pointer",
    fontWeight: 600,
    width: 'fit-content',
    color: "#000",
    // display: "flex",
    // justifyContent: 'center',
    // alignItems: 'center',
    height: "50px",
    lineHeight: "50px",
    margin: "0",
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    // padding: "0 28px",
    textAlign: 'center',
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
  },
  buttonContainer: {
    display: 'flex',
    flexDirection: 'column',
    // justifyContent: 'space-around',
    // alignItems: 'center',
  },
  availableTag: {
    padding: "10px",
    backgroundColor: "#aaffaa",
    borderRadius: "10px",
    color: "#1dcf1d",
    fontWeight: 800,
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  outTag: {
    padding: "10px",
    backgroundColor: "#ffaaaa",
    borderRadius: "10px",
    color: "#e84343",
    fontWeight: 800,
    marginBottom: 10,
    alignSelf: 'flex-start',
  },

  firstRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  secondRow: {
    display: 'flex',
    width: "23%",
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: "-40px",
  },

  heartContainer: {
    display: 'flex',
    marginTop: 10,
  },
  likes: {
    marginRight: "15px",
    marginTop: "5px",
  },
}));
