import Head from 'next/head';
import React, { useContext, useEffect, useState } from 'react';
import { Header } from '../../src/main-page/header/Header';
import { ToggleButton } from '../../src/profile/ToggleButton';
import { useStyles } from '../../styles/profile-page-styles';
// eslint-disable-next-line import/no-cycle
import { Table } from '../../src/profile/table/Table';
import ProfileSection from '../../src/profile/profile-section/ProfileSection';
import { InfoContext } from "../../src/contexts/InfoContext";
import { axiosInstance } from '../../src/axiosConfig';

export interface Invoice {
  id: number
  traceNumber: string;
  state: number;
  book: {id: number; name: string};
  user: {firstName: string, lastName: string}
  dateCreated: string;
  dueDate: string;
}

export default function Profile() {
  const [toggle, setToggle] = useState<number>(0);
  const [invoices, setInvoices] = useState<Invoice[]>([]);

  const handleChange = (value: number) => setToggle(value);

  const classes = useStyles();

  const info = useContext(InfoContext);

  useEffect(() => {
    if (info.isLoggedin) return;
    window.location.replace('./');
  }, [info]);

  useEffect(() => {
    const get = async () => {
      try {
        const res = await axiosInstance.get('/rent/user');
        setInvoices(res.data.data);
      } catch (err) {
        console.error(err);
      }
    };
    get();
  }, []);

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={classes.main}>
        {toggle === 0
          ? (
            <div style={{ margin: 20 }}>
              <ProfileSection toggle={toggle} handleToggle={handleChange} />
            </div>
          ) : (
            <div style={{
              width: "80%",
              margin: 20,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
            }}
            >
              <p className={classes.greeting}>
                {`${"کاربر"} عزیز، خوش آمدید`}
              </p>
              <ToggleButton
                labels={['رسیدها', 'پروفایل'].reverse()}
                value={toggle}
                onChange={handleChange}
              />
              <Table
                tableHeaders={['کد پیگیری', 'کتاب', 'تاریخ تحویل', 'موعد بازگشت']}
                data={invoices}
              />
            </div>
          )}
      </div>
      <footer className={classes.footer}>
        تمامی حقوق برای سازندگان محفوظ است. .
      </footer>
    </div>
  );
}
