import { createStyles, makeStyles } from "@material-ui/core";

export const useStyles = makeStyles(() => createStyles({
  container: {
    minHeight: "100vh",
    padding: "0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    backgroundColor: "#f7f7f7",
    alignItems: "center",
    maxWidth: "100%",
    direction: "rtl",
  },
  row: {
    display: 'flex',
  },
  main: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: "100%",
    margin: "50px 0",
    minHeight: "calc(100vh - 130px)",
    '& > p': {
      fontSize: 18,
      marginBottom: 30,
      color: "#02c3d9",
    },
  },
  greeting: {
    fontWeight: 600,
    fontSize: "140%",
    marginLeft: 5,
    marginBottom: 20,
    color: "#000 !important",
  },
  button: {
    backgroundColor: "#ffd52e",
    borderRadius: "25px",
    border: "none",
    boxSizing: "border-box",
    cursor: "pointer",
    fontWeight: 600,
    display: "inline-block",
    height: 40,
    width: 150,
    marginTop: 30,
    maxWidth: "100%",
    overflow: "hidden",
    outline: "none",
    position: "relative",
    textAlign: "center",
    textOverflow: "ellipsis",
    transition: "background-color 0.2s, opacity 0.2s",
    whiteSpace: "nowrap",
    '&:hover': {
      backgroundColor: '#e6c029',
    },
  },
  footer: {
    height: "80px",
    position: "relative",
    backgroundColor: "#333",
    color: "#fff",
    bottom: "0",
    width: "100%",
    marginTop: "auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
}));
