import Head from 'next/head';
import React, {
  useContext, useState, useEffect,
} from 'react';
import { Header } from '../../src/main-page/header/Header';
import { ToggleButton } from '../../src/profile/ToggleButton';
import { useStyles } from '../../styles/admin-page-styles';
import { CategoryTable } from '../../src/admin-profile/table/CategoryTable';
import { BookTab } from '../../src/admin-profile/book-list/BookTab';
import { InvoiceTable } from '../../src/admin-profile/table/InvoiceTable';

import { InfoContext } from "../../src/contexts/InfoContext";

export default function Profile() {
  const [toggle, setToggle] = useState<number>(0);

  const handleChange = (value: number) => setToggle(value);

  const classes = useStyles();

  const info = useContext(InfoContext);

  useEffect(() => {
    if (info.isAdmin) return;
    window.location.replace('./');
  }, [info]);

  const getMainComponent = (toggleVal: number) => {
    switch (toggleVal) {
      case 0:
        return (
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
          }}
          >
            <BookTab />
          </div>
        );
      case 1:
        return (
          <CategoryTable
            tableHeaders={['id', 'نام‌ دسته‌بندی']}
          />
        );

      case 2:
        return (
          <InvoiceTable
            tableHeaders={['کد پیگیری', 'کتاب', 'نام گیرنده', 'وضعیت', 'تاریخ تحویل', 'موعد برگشت', '', '', '']}
          />
        );
      default: return <div />;
    }
  };

  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={classes.main}>
        <p className={classes.greeting}>
          ادمین عزیز، خوش آمدید
        </p>
        <ToggleButton
          labels={['لیست کتابها', 'لیست دسته‌ها', 'رسیدها']}
          value={toggle}
          onChange={handleChange}
        />
        <div style={{ margin: 20 }}>
          {getMainComponent(toggle)}
        </div>
        <footer className={classes.footer}>
          تمامی حقوق برای سازندگان محفوظ است. .
        </footer>
      </div>
    </div>
  );
}
